services:
  mongodb:
    image: mongo:8.0
    container_name: bf-mongodb
    ports:
      - '27018:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=bullfood
    volumes:
      - mongodb-data:/data/db
    networks:
      - service-network

  redis:
    image: redis:7.4-alpine
    container_name: bf-redis
    ports:
      - '6379:6379'
    entrypoint: redis-server --appendonly yes
    networks:
      - service-network

  rabbitmq:
    image: rabbitmq:4.0.3-management-alpine
    container_name: bf-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - service-network
volumes:
  mongodb-data:

networks:
  service-network:
    driver: bridge
