name: Node.js API server CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/**'
      - '.github/workflows/**'  
  pull_request:
    branches: [ "main" ]
    paths:
      - 'server/**'
      - '.github/workflows/**' 

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    defaults:
      run:
        working-directory: ./server

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
